# Generated by Django 5.1.15 on 2026-09-24 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyWardenAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_tenants', models.BooleanField(default=True)),
                ('can_manage_rooms', models.BooleanField(default=True)),
                ('can_view_payments', models.BooleanField(default=True)),
                ('can_manage_expenses', models.BooleanField(default=True)),
                ('can_view_maintenance', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warden_assignments', to='properties.property')),
                ('warden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warden_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property Warden Assignment',
                'verbose_name_plural': 'Property Warden Assignments',
                'db_table': 'property_warden_assignments',
                'unique_together': {('warden', 'property')},
            },
        ),
    ]
