# Generated by Django 5.1.15 on 2026-09-24 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_month', models.CharField(db_index=True, max_length=7)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_tenants_billed', models.PositiveIntegerField(default=0)),
                ('total_amount_billed', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_cycles', to='properties.property')),
            ],
            options={
                'verbose_name': 'Rent Cycle',
                'verbose_name_plural': 'Rent Cycles',
                'db_table': 'rent_cycles',
                'ordering': ['-billing_month'],
                'unique_together': {('pg', 'billing_month')},
            },
        ),
    ]
