# Generated by Django 5.1.15 on 2026-09-24 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('rooms', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('furniture', 'Furniture'), ('appliance', 'Appliance'), ('cleaning', 'Cleaning'), ('pest', 'Pest'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('inProgress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('cost_incurred', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='properties.property')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='rooms.room')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Maintenance Ticket',
                'verbose_name_plural': 'Maintenance Tickets',
                'db_table': 'maintenance_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
