# Generated by Django 5.1.15 on 2026-09-24 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beds', '0001_initial'),
        ('properties', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=255)),
                ('id_number', models.CharField(blank=True, default='', max_length=100)),
                ('id_type', models.CharField(choices=[('citizenship', 'Citizenship'), ('passport', 'Passport'), ('drivingLicense', 'Driving License'), ('nationalId', 'National ID'), ('studentId', 'Student ID'), ('other', 'Other')], default='citizenship', max_length=50)),
                ('id_image_path', models.TextField(blank=True, default='')),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deposit_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('move_in_date', models.DateField()),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('notice', 'Notice'), ('graduated', 'Graduated')], db_index=True, default='active', max_length=20)),
                ('guardian_name', models.CharField(blank=True, default='', max_length=255)),
                ('guardian_phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tenants', to='beds.bed')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='properties.property')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='rooms.room')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'ordering': ['-created_at'],
            },
        ),
    ]
