# Generated by Django 5.1.15 on 2026-09-25 17:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half-Yearly'), ('yearly', 'Yearly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='late_fee_type',
            field=models.CharField(choices=[('none', 'None'), ('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='late_fee_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
