# Generated by Django 5.1.15 on 2026-09-25 17:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_invoice_numbers(apps, schema_editor):
    """Assign unique INV-LEGACY-NNNNNN numbers to existing invoices."""
    Invoice = apps.get_model("payments", "Invoice")
    for idx, invoice in enumerate(Invoice.objects.order_by("id"), start=1):
        if not invoice.invoice_number:
            invoice.invoice_number = f"INV-LEGACY-{idx:06d}"
            invoice.save(update_fields=["invoice_number"])


def backfill_receipt_numbers(apps, schema_editor):
    """Assign unique RCP-LEGACY-NNNNNN numbers to existing payments."""
    Payment = apps.get_model("payments", "Payment")
    for idx, payment in enumerate(Payment.objects.order_by("id"), start=1):
        if not payment.receipt_number:
            payment.receipt_number = f"RCP-LEGACY-{idx:06d}"
            payment.save(update_fields=["receipt_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0002_initial'),
        ('payments', '0001_initial'),
        ('properties', '0001_initial'),
        ('rooms', '0001_initial'),
        ('tenants', '0002_tenant_billing_frequency_tenant_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('invoice_created', 'Invoice Created'), ('invoice_updated', 'Invoice Updated'), ('invoice_voided', 'Invoice Voided'), ('payment_recorded', 'Payment Recorded'), ('payment_allocated', 'Payment Allocated'), ('payment_voided', 'Payment Voided'), ('status_changed', 'Status Changed')], db_index=True, max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'billing_audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Allocation',
                'verbose_name_plural': 'Payment Allocations',
                'db_table': 'payment_allocations',
                'ordering': ['allocated_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='beds.bed'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
        # Add invoice_number WITHOUT unique=True first so backfill can run
        migrations.AddField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        # Backfill existing rows with unique values
        migrations.RunPython(backfill_invoice_numbers, migrations.RunPython.noop),
        # Now apply the unique constraint
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_voided',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_voided',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        # Add receipt_number WITHOUT unique=True first
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        # Backfill existing payments with unique receipt numbers
        migrations.RunPython(backfill_receipt_numbers, migrations.RunPython.noop),
        # Now apply the unique constraint
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('partial', 'Partial'), ('void', 'Void')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_voided', False), ('period_end__isnull', False), ('period_start__isnull', False), ('type', 'rent')), fields=('tenant', 'type', 'period_start', 'period_end'), name='unique_rent_invoice_per_period'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='pg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='properties.property'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.invoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('payment', 'invoice')},
        ),
    ]
